restaureant/newproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant_menu.urls'))
]

restaureant/restaurant_menu/urls.py
from django.urls import path
from . import views
urlpatterns= [
    path('', views.MenuList.as_view(), name="home"),
    path('item/<int:pk>/', views.MenuItemDetails.as_view(), name="menu_item"),
    path('item/about', views.about, name='about')
]

# item/<int:pk> syntax of the django to handle dynamic urls

restaureant/restaurant_menu/models.py
from django.db import models
from django.contrib.auth.models import User
MEAL_TYPE= (
    ('starters', 'Starters'),
    ('salads', 'Salads'),
    ('main_dishes', "Main Dishes"),
    ('desserts', 'Desserts')
)
STATUS = (
    (0, "Unavaible"),
    (1,"Available")
)

class Item(models.Model):
    meal= models.CharField(max_length=1000, unique=True)
    discription= models.CharField(max_length=1500)
    price= models.DecimalField(decimal_places=2, max_digits=10)
    meal_type= models.CharField(choices=MEAL_TYPE, max_length=100)
    author= models.ForeignKey(User,on_delete=models.PROTECT)
    status= models.IntegerField(choices=STATUS, default=1)
    date_created= models.DateTimeField(auto_now_add=True)
    date_updated= models.DateField(auto_now=True)


restaureant/restaurant_menu/views.py
from django.shortcuts import render
from django.views import generic
from .models import Item, MEAL_TYPE

class MenuList(generic.ListView):
    queryset= Item.objects.order_by("date_created")
    template_name= "index.html"

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context["meal_type"]= MEAL_TYPE
        return context

class MenuItemDetails(generic.DetailView):
    model= Item
    template_name= "menu_item_detail.html"

def about(request):
    return render(request, "about.html")

restaureant/restaurant_menu/templates/about.html
{% extends 'base.html' %}
{% block content %}
<style>
        body {
        font-family: Arial, Helvetica, sans-serif;
        margin: 0;
        }

        html {
        box-sizing: border-box;
        }

        *, *:before, *:after {
        box-sizing: inherit;
        }

        .column {
        float: left;
        width: 33.3%;
        margin-bottom: 16px;
        padding: 0 8px;
        }

        .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        margin: 8px;
        }

        .about-section {
        padding: 50px;
        text-align: center;
        background-color: #474e5d;
        color: white;
        }

        .container {
        padding: 0 16px;
        }

        .container::after, .row::after {
        content: "";
        clear: both;
        display: table;
        }

        .title {
        color: grey;
        }

        .button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
        }

        .button:hover {
        background-color: #555;
        }

        @media screen and (max-width: 650px) {
        .column {
            width: 100%;
            display: block;
        }
        }
</style>
</head>
<body>

<div class="about-section">
<h1>About Us</h1>
<p>Our HL Restaurant is a well-known Restaurant in Jaipur</p>
<p></p>
</div>

<h2 style="text-align:center">Our Team</h2>
<div class="row">
<div class="column">
    <div class="card">
    <div class="container"> <br>
        <h2>Hitesh Lalwani</h2>
        <p class="title">CEO & Founder</p>
        <p>Completed Bachelor's in Computer Science from University of Rajasthan.</p>
        <p>hiteshlalwani3060@gmail.com</p>
        <p><button class="button">Contact</button></p>
    </div>
    </div>
</div>

<div class="column">
    <div class="card">
    <div class="container"> <br>
        <h2>Ardit Sulce</h2>
        <p class="title">Art Director</p>
        <p>Teacher in Udemy.com</p> <br>
        <p>ardit@example.com</p>
        <p><button class="button">Contact</button></p>
    </div>
    </div>
</div>

<div class="column">
    <div class="card">
    <div class="container"> <br>
        <h2>Dimple Lalwani</h2>
        <p class="title">Designer</p>
        <p>Currently Doing B.COM from Maharani College</p> <br>
        <p>dimple56@gmail.com</p>
        <p><button class="button">Contact</button></p>
    </div>
    </div>
</div>
        </div>
{% endblock %}

restaureant/restaurant_menu/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <title>Menu Products</title>
        <style>
            .rounded-pill{
                margin: 0px 0px 0px 35px;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                    <a class="navbar-brand" href="#"></a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                         <span class="navbar-toggler-icon"></span>
                    </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                         <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'about' %}">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
        {% endblock content %}

<!-- JavaScript Bundle with Popper -->
             <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    </body>
</html>

restaureant/restaurant_menu/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2>Restaurent Menu</h2>
    <ul class="list-group list-group-flush"></ul>
        {% for meal_ty in meal_type %}
            <h3 class="pt-5">{{ meal_ty.1 }}</h3>
            {% for m in item_list %} 
                {% if m.meal_type == meal_ty.0 %}
                    {% if m.status == 0 %}
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
                            <del><a href='{% url "menu_item" m.pk %}'>{{m.meal}}</a></del></h4>
                            <span class="badge bg-primary rounded-pill">Rs {{ m.price }}</span>
                        </li>
                        <li class="list-group-item pt-0">
                        <p>{{m.discription}}</p>
                        </li>
                    {% else %}
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
                            <a href='{% url "menu_item" m.pk %}'>{{m.meal}}</a>
                            <span class="badge bg-primary rounded-pill"> Rs {{ m.price }}</span>
                        </li>
                        <li class="list-group-item pt-0">
                            <p>{{m.discription}}</p>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
        {% endfor %}
</div>
{% endblock content %}

restaureant/restaurant_menu/templates/menu_item_detail.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
</head>
<body>
        <div class="container">
        <h3 class="pt-5">{{ item.meal }}</h3>
        <ul cl2ass="list-group list-group-flush">
            <li class="list-group-item pt-0" >{{ item.discription }} <span class="badge bg-primary rounded-pill">Rs {{ item.price }}</span></li>
            
        </ul>
        {% if item.status == 1 %}
            <button onclick="change()" class="btn btn-secondary">Order</button>
        
        {% else %}
        <button onclick="change()" class="btn btn-secondary" disabled>Order</button> <br> <br>
        {% endif %}
        </div>
        <br> <br>
        <div id="change"></div>
    <script>
        function change(){

            document.getElementById("change").innerHTML=`<div class="alert alert-success">Thank You for Your order. Your order is placed</div>`
        }
    </script>
</body>
</html>
{% endblock content %}